### ISSUE TITLE
Search unicode and ascii string

### ISSUE THREAD

**Issue by GermanAizek** [JeanExtreme002/PyMemoryEditor#4]
@JeanExtreme002, hi. How to search unicode and ascii string?  There are not enough examples.

**Comment by JeanExtreme002** [comment]
Just use the method `search_by_value`, passing the type `str`, length of the string and the target string.

```
target = "Hello World"

for addr in p.search_by_value(str, len(target), target):
    print("Found target at:", addr)
```

**Comment by GermanAizek** [comment]
@JeanExtreme002, i tried this. Unicode len(target) * 2? Crysearch and cheat engine found 4 ascii value and 1 unicode str value. Im use your

```py
with OpenProcess(..
  while(True):
    for addr in p.search_by_...
```
how well do I use the loop to infinite search?

**Comment by JeanExtreme002** [comment]
For unicode values, use type `bytes` with `len(target) * 2`.

```
for addr in p.search_by_value(bytes, len(target) * 2, target):
    print("Found target at:", addr)
```

**Comment by GermanAizek** [comment]
Many thanks for additional information.
